BEGIN;

ALTER TABLE public.retail_checkins
    ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 7) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS longitude NUMERIC(10, 7) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS location_accuracy NUMERIC(8, 2) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS google_maps_url TEXT DEFAULT NULL;

COMMIT;
